apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: eks-service-account
      containers:
      - name: backend
        image: 051826710466.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-region
              key: AWS_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service 
  labels:
    app: backend 
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-service-monitor
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  selector:
    matchLabels:
      app: backend
