apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: eks-service-account
      containers:
      - name: backend
        image: 051826710466.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-region
              key: AWS_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service  
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: 
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      