metrics:
    port: 10254
    portName: metrics
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true    
    
    serviceMonitor:
      enabled: true
      additionalLabels: {
        release: prometheus
      }
      