name: Build frontend image and push to AWS ECR
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: "Build and Push Docker Image to ECR"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::051826710466:role/github_ecr

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build, tag, and push the Docker image to Amazon ECR
      - name: Build, Tag, and Push Docker Image
        id: build-and-push
        run: |
          docker build -t discography/frontend .
          docker push 051826710466.dkr.ecr.us-east-1.amazonaws.com/discography/frontend:latest
